from pathlib import Path
from PIL import Image
import re
import sys

THRESHOLD = 128

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent

INPUT_DIR = SCRIPT_DIR / "input"
OUTPUT_FILE = PROJECT_DIR / "src" / "assets" / "frames.h"


def make_identifier(filename: str) -> str:
    """Convert a filename into a valid uppercase C++ identifier."""
    name = Path(filename).stem.upper()
    name = re.sub(r"[^A-Z0-9_]", "_", name)

    if name and name[0].isdigit():
        name = "_" + name

    return f"FRAME_{name}"


def image_to_bitmap(image: Image.Image) -> list[int]:
    """Convert an image to an Adafruit GFX compatible monochrome bitmap."""
    image = image.convert("L")

    width = image.width
    height = image.height
    bitmap = []

    for y in range(height):
        for x_start in range(0, width, 8):
            value = 0

            for bit in range(8):
                x = x_start + bit

                if x >= width:
                    continue

                pixel = image.getpixel((x, y))

                # Dark PNG pixels become active OLED pixels.
                if pixel >= THRESHOLD:
                    value |= 1 << (7 - bit)

            bitmap.append(value)

    return bitmap


def format_bitmap(bitmap: list[int]) -> str:
    """Format bitmap bytes as a readable C++ array."""
    lines = []

    for i in range(0, len(bitmap), 16):
        chunk = bitmap[i:i + 16]
        lines.append("    " + ", ".join(f"0x{byte:02X}" for byte in chunk))

    return ",\n".join(lines)


def convert_file(path: Path) -> tuple[str, int, int, list[int]]:
    """Load and convert a single PNG file."""
    with Image.open(path) as image:
        if image.width <= 0 or image.height <= 0:
            raise ValueError(f"{path.name}: invalid image size")

        identifier = make_identifier(path.name)
        width = image.width
        height = image.height
        bitmap = image_to_bitmap(image)

    return identifier, width, height, bitmap


def generate_header(frames: list[tuple[str, int, int, list[int]]]) -> str:
    """Generate the complete frames.h header file."""
    output = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        '#include "bitmap.h"',
        "",
        "/**",
        " * @file frames.h",
        " * @brief Auto-generated NetPet bitmap data.",
        " *",
        " * Generated by tools/convertor.py.",
        " * Do not edit this file manually.",
        " */",
        ""
    ]

    for identifier, width, height, bitmap in frames:
        data_identifier = f"{identifier}_DATA"

        output.extend([
            "/**",
            f" * @brief Bitmap data for {identifier} ({width}x{height}).",
            " */",
            f"const uint8_t {data_identifier}[] PROGMEM = {{",
            format_bitmap(bitmap),
            "};",
            "",
            f"const Bitmap {identifier} = {{",
            f"    {data_identifier},",
            f"    {width},",
            f"    {height}",
            "};",
            ""
        ])

    return "\n".join(output)


def main():
    """Convert all PNG files in input/ into src/assets/frames.h."""
    print()
    print("NetPet Bitmap Converter")
    print("=======================")
    print(f"Script:  {SCRIPT_DIR}")
    print(f"Project: {PROJECT_DIR}")
    print(f"Input:   {INPUT_DIR}")
    print(f"Output:  {OUTPUT_FILE}")
    print()

    INPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    files = sorted(INPUT_DIR.glob("*.png"))

    if not files:
        print("[ERROR] No PNG files found.")
        print(f"Place your PNG files in:")
        print(INPUT_DIR)
        sys.exit(1)

    frames = []

    for path in files:
        try:
            identifier, width, height, bitmap = convert_file(path)
            frames.append((identifier, width, height, bitmap))

            print(
                f"[OK] {path.name:<30} "
                f"{width:>3}x{height:<3} -> {identifier}"
            )

        except Exception as error:
            print(f"[ERROR] {error}")
            sys.exit(1)

    header = generate_header(frames)
    OUTPUT_FILE.write_text(header, encoding="utf-8")

    print()
    print(f"[DONE] Generated {len(frames)} bitmap(s)")
    print(f"[DONE] Written to: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()