from pathlib import Path
from PIL import Image
import re
import sys

FRAME_WIDTH = 128
FRAME_HEIGHT = 48
THRESHOLD = 128

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent

INPUT_DIR = SCRIPT_DIR / "input"
OUTPUT_FILE = PROJECT_DIR / "src" / "assets" / "frames.h"


def make_identifier(filename: str) -> str:
    """Convert a filename into a valid uppercase C++ identifier."""
    name = Path(filename).stem.upper()
    name = re.sub(r"[^A-Z0-9_]", "_", name)

    if name and name[0].isdigit():
        name = "_" + name

    return f"FRAME_{name}"


def image_to_bitmap(image: Image.Image) -> list[int]:
    """Convert an image to an Adafruit GFX compatible monochrome bitmap."""
    image = image.convert("L")
    bitmap = []

    for y in range(FRAME_HEIGHT):
        for x_start in range(0, FRAME_WIDTH, 8):
            value = 0

            for bit in range(8):
                x = x_start + bit
                pixel = image.getpixel((x, y))

                if pixel >= THRESHOLD:
                    value |= 1 << (7 - bit)

            bitmap.append(value)

    return bitmap


def format_bitmap(bitmap: list[int]) -> str:
    """Format bitmap bytes as a readable C++ array."""
    lines = []

    for i in range(0, len(bitmap), 16):
        chunk = bitmap[i:i + 16]
        lines.append("    " + ", ".join(f"0x{byte:02X}" for byte in chunk))

    return ",\n".join(lines)


def convert_file(path: Path) -> tuple[str, list[int]]:
    """Load and convert a single PNG file."""
    with Image.open(path) as image:
        if image.size != (FRAME_WIDTH, FRAME_HEIGHT):
            raise ValueError(
                f"{path.name}: expected {FRAME_WIDTH}x{FRAME_HEIGHT}, "
                f"got {image.width}x{image.height}"
            )

        identifier = make_identifier(path.name)
        bitmap = image_to_bitmap(image)

    return identifier, bitmap


def generate_header(frames: list[tuple[str, list[int]]]) -> str:
    """Generate the complete frames.h header file."""
    output = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "/**",
        " * @file frames.h",
        " * @brief Auto-generated NetPet animation frame data.",
        " *",
        " * Generated by tools/frame_converter/convert.py.",
        " * Do not edit this file manually.",
        " */",
        "",
        f"constexpr uint8_t FRAME_WIDTH = {FRAME_WIDTH};",
        f"constexpr uint8_t FRAME_HEIGHT = {FRAME_HEIGHT};",
        "constexpr size_t FRAME_SIZE = (FRAME_WIDTH * FRAME_HEIGHT) / 8;",
        ""
    ]

    for identifier, bitmap in frames:
        output.extend([
            "/**",
            f" * @brief Animation frame: {identifier}.",
            " */",
            f"const uint8_t {identifier}[FRAME_SIZE] PROGMEM = {{",
            format_bitmap(bitmap),
            "};",
            ""
        ])

    return "\n".join(output)


def main():
    """Convert all PNG files in input/ into src/assets/frames.h."""
    print()
    print("NetPet Frame Converter")
    print("======================")
    print(f"Script:  {SCRIPT_DIR}")
    print(f"Project: {PROJECT_DIR}")
    print(f"Input:   {INPUT_DIR}")
    print(f"Output:  {OUTPUT_FILE}")
    print()

    INPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    files = sorted(INPUT_DIR.glob("*.png"))

    if not files:
        print("[ERROR] No PNG files found.")
        print(f"Place your 128x48 PNG files in:")
        print(INPUT_DIR)
        sys.exit(1)

    frames = []

    for path in files:
        try:
            identifier, bitmap = convert_file(path)
            frames.append((identifier, bitmap))
            print(f"[OK] {path.name} -> {identifier}")

        except Exception as error:
            print(f"[ERROR] {error}")
            sys.exit(1)

    header = generate_header(frames)
    OUTPUT_FILE.write_text(header, encoding="utf-8")

    print()
    print(f"[DONE] Generated {len(frames)} frame(s)")
    print(f"[DONE] Written to: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()